import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Check, Plus } from "lucide-react";
import { loadData, balance, paid } from "@/lib/data";
import { dateLabel, money } from "@/lib/format";
import { variantLabel } from "@/lib/variants";
import { Alert, Back, Heading, SaleStatus } from "@/components/ui";
export default async function SaleDetail({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; ok?: string }> }) {
  const { id } = await params; const { error, ok } = await searchParams; const { sales, customers, items, payments } = await loadData();
  const sale = sales.find(s => s.id === id); if (!sale) notFound(); const customer = customers.find(c => c.id === sale.customer_id); const remaining = balance(sale, payments); const receipts = payments.filter(p => p.sale_id === sale.id);
  return <><Back href="/ventas" /><Heading eyebrow={`VENTA · ${dateLabel(sale.created_at)}`} title={customer ? `Compra de ${customer.name}` : "Venta de mostrador"} description="Productos entregados y pagos recibidos." action={remaining > 0 ? <Link href={`/ventas/${id}/abonar`} className="button primary"><Plus size={18} /> Registrar abono</Link> : <span className="button done"><Check size={18} /> Venta pagada</span>} /><Alert error={error} ok={ok} />
  <div className="sale-detail-grid"><section className="panel"><div className="panel-header"><div><span className="eyebrow">PRODUCTOS ENTREGADOS</span><h2>Detalle de la compra</h2></div><SaleStatus balance={remaining} total={sale.total} /></div><div className="detail-items">{items.filter(i => i.sale_id === id).map(i => <div key={i.id}><span><strong>{i.product_name}</strong>{variantLabel(i.variant_color, i.variant_size) && <small>{variantLabel(i.variant_color, i.variant_size)}</small>}<small>{i.quantity} × {money(i.unit_price)}</small></span><strong>{money(i.quantity * i.unit_price)}</strong></div>)}</div><div className="detail-totals"><div><span>Total de la venta</span><strong>{money(sale.total)}</strong></div><div><span>Pagado</span><strong>{money(paid(id, payments))}</strong></div><div className="detail-outstanding"><span>Queda por pagar</span><strong>{money(remaining)}</strong></div></div></section>
  <section className="panel"><div className="panel-header"><div><span className="eyebrow">DINERO RECIBIDO</span><h2>Historial de pagos</h2></div></div>{receipts.length ? <div className="row-list">{receipts.map(p => <div key={p.id} className="list-row"><span className="avatar muted-avatar">$</span><span className="list-primary"><strong>{sale.customer_id ? "Abono" : "Pago completo"}</strong><small>{dateLabel(p.paid_at)}{p.note ? ` · ${p.note}` : ""}</small></span><strong className="positive-value">+ {money(p.amount)}</strong></div>)}</div> : <div className="empty-inline pad">Todavía no se han recibido pagos para esta venta.</div>}{customer && <Link href={`/clientes/${customer.id}`} className="panel-footer-link">Ver ficha de {customer.name} <ArrowRight size={16} /></Link>}</section></div></>;
}
